services:
  nginx:
    image: nginx:1.24
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./public:/public
      # - ./logs/nginx:/var/log/nginx # ホスト側にログをマウントする
      - ./etc/nginx/nginx-logrotate.sh:/nginx-logrotate.sh
    ports:
      - "80:80"
    links:
      - varnish

  varnish:
    image: varnish
    tmpfs:
      - /var/lib/varnish/varnishd:exec
    volumes:
      - ./etc/varnish:/etc/varnish
    links:
       - app

  app:
    # Go実装の場合は golang/ PHP実装の場合は php/
    build: ruby/
    environment:
      ISUCONP_DB_HOST: mysql
      ISUCONP_DB_PORT: 3306
      ISUCONP_DB_USER: root
      ISUCONP_DB_PASSWORD: root
      ISUCONP_DB_NAME: isuconp
      ISUCONP_MEMCACHED_ADDRESS: memcached:11211
    links:
      - mysql
      - memcached
    volumes:
      - ./public:/home/public
    init: true
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1g
    ports:
      - "8080:8080"

  mysql:
    image: mysql:8.0
    environment:
      #- "TZ=Asia/Tokyo"
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - mysql:/var/lib/mysql
      - ./etc/my.cnf:/etc/my.cnf
      - ./sql:/docker-entrypoint-initdb.d
      #- ./logs/mysql:/var/log/mysql
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1g

  memcached:
    image: memcached:1.6

volumes:
  mysql:
